const {
  VITE_GOOGLE_MAPS_API_KEY: GOOGLE_API_KEY,
  VITE_FIREBASE_API_KEY: FIREBASE_API_KEY,
  VITE_FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  VITE_FIREBASE_PROJECT_ID: FIREBASE_PROJECT_ID,
  VITE_FIREBASE_STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
  VITE_FIREBASE_MESSAGING_SENDER_ID: FIREBASE_MESSAGING_SENDER_ID,
  VITE_FIREBASE_APP_ID: FIREBASE_APP_ID,
  VITE_FIREBASE_MEASUREMENT_ID: FIREBASE_MEASUREMENT_ID,
  VITE_FEEDBACK_ID: FEEDBACK_ID,
  VITE_SENTRY_DSN: SENTRY_DSN,
} = import.meta.env;

const env = {
  GOOGLE_API_KEY,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
  FEEDBACK_ID,
  SENTRY_DSN,
};

export default env;
